/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.udesc.ppr55.sr.view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Robson
 */
public class Tabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form Tabuleiro
     */
    public Tabuleiro() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);//executar com a tela inteira
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blnEncerrar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPontuacaoUser1 = new javax.swing.JLabel();
        lblPontuacaoUser2 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        lblUser1 = new javax.swing.JLabel();
        lblUser2 = new javax.swing.JLabel();
        btnPlaye2One = new javax.swing.JButton();
        btnPlaye2Two = new javax.swing.JButton();
        btnPlaye2Three = new javax.swing.JButton();
        btnPlaye2Four = new javax.swing.JButton();
        btnPlaye2Five = new javax.swing.JButton();
        panelTabuleiro = new javax.swing.JPanel();
        btnPeca2 = new javax.swing.JButton();
        btnPeca3 = new javax.swing.JButton();
        btnPeca4 = new javax.swing.JButton();
        btnPeca5 = new javax.swing.JButton();
        btnPeca6 = new javax.swing.JButton();
        btnPeca7 = new javax.swing.JButton();
        btnPeca8 = new javax.swing.JButton();
        btnPeca9 = new javax.swing.JButton();
        btnPeca10 = new javax.swing.JButton();
        btnPeca11 = new javax.swing.JButton();
        btnPeca12 = new javax.swing.JButton();
        btnPeca13 = new javax.swing.JButton();
        btnPeca14 = new javax.swing.JButton();
        btnPeca15 = new javax.swing.JButton();
        btnPeca16 = new javax.swing.JButton();
        btnPeca17 = new javax.swing.JButton();
        btnPeca18 = new javax.swing.JButton();
        btnPeca19 = new javax.swing.JButton();
        btnPeca20 = new javax.swing.JButton();
        btnPeca26 = new javax.swing.JButton();
        btnPeca27 = new javax.swing.JButton();
        btnPeca28 = new javax.swing.JButton();
        btnPeca29 = new javax.swing.JButton();
        btnPeca30 = new javax.swing.JButton();
        btnPeca31 = new javax.swing.JButton();
        btnPeca32 = new javax.swing.JButton();
        btnPeca33 = new javax.swing.JButton();
        btnPeca34 = new javax.swing.JButton();
        btnPeca35 = new javax.swing.JButton();
        btnPeca36 = new javax.swing.JButton();
        btnPeca37 = new javax.swing.JButton();
        lblCube1 = new javax.swing.JButton();
        lblCube2 = new javax.swing.JButton();
        lblCube4 = new javax.swing.JButton();
        lblCube3 = new javax.swing.JButton();
        lblCube6 = new javax.swing.JButton();
        lblCube7 = new javax.swing.JButton();
        lblCube8 = new javax.swing.JButton();
        lblCube11 = new javax.swing.JButton();
        lblCube12 = new javax.swing.JButton();
        lblCube10 = new javax.swing.JButton();
        lblCube13 = new javax.swing.JButton();
        btnContract3 = new javax.swing.JButton();
        btnContract1 = new javax.swing.JButton();
        btnContract6 = new javax.swing.JButton();
        btnContract5 = new javax.swing.JButton();
        btnContract4 = new javax.swing.JButton();
        btnContract2 = new javax.swing.JButton();
        lblCube5 = new javax.swing.JButton();
        lblCube9 = new javax.swing.JButton();
        lblCube14 = new javax.swing.JButton();
        btnPeca38 = new javax.swing.JButton();
        blnBolsaCube = new javax.swing.JButton();
        blnBolsaContract = new javax.swing.JButton();
        blnBolsaMoeda = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnPlaye1One = new javax.swing.JButton();
        btnPlaye1Two = new javax.swing.JButton();
        btnPlaye1Three = new javax.swing.JButton();
        btnPlaye1Four = new javax.swing.JButton();
        btnPlaye1Five = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blnEncerrar.setForeground(new java.awt.Color(255, 0, 0));
        blnEncerrar.setText("Encerrar");
        blnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blnEncerrarActionPerformed(evt);
            }
        });

        btnIniciar.setForeground(new java.awt.Color(51, 204, 0));
        btnIniciar.setText("Iniciar ");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("Player 1:");

        jLabel2.setText("Player 2: ");

        jLabel3.setText("Pontuação: ");

        jLabel4.setText("Pontuação: ");

        btnReiniciar.setForeground(new java.awt.Color(0, 0, 204));
        btnReiniciar.setText("Reiniciar");

        lblUser1.setText("nome...");

        lblUser2.setText("nome...");

        btnPlaye2One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye2OneActionPerformed(evt);
            }
        });

        btnPlaye2Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye2TwoActionPerformed(evt);
            }
        });

        btnPlaye2Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye2ThreeActionPerformed(evt);
            }
        });

        btnPlaye2Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye2FourActionPerformed(evt);
            }
        });

        btnPlaye2Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye2FiveActionPerformed(evt);
            }
        });

        btnPeca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca2ActionPerformed(evt);
            }
        });

        btnPeca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca3ActionPerformed(evt);
            }
        });

        btnPeca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca4ActionPerformed(evt);
            }
        });

        btnPeca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca5ActionPerformed(evt);
            }
        });

        btnPeca6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca6ActionPerformed(evt);
            }
        });

        btnPeca7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca7ActionPerformed(evt);
            }
        });

        btnPeca8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca8ActionPerformed(evt);
            }
        });

        btnPeca9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca9ActionPerformed(evt);
            }
        });

        btnPeca10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca10ActionPerformed(evt);
            }
        });

        btnPeca11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca11ActionPerformed(evt);
            }
        });

        btnPeca12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca12ActionPerformed(evt);
            }
        });

        btnPeca13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca13ActionPerformed(evt);
            }
        });

        btnPeca14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca14ActionPerformed(evt);
            }
        });

        btnPeca15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca15ActionPerformed(evt);
            }
        });

        btnPeca16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca16ActionPerformed(evt);
            }
        });

        btnPeca17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca17ActionPerformed(evt);
            }
        });

        btnPeca18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca18ActionPerformed(evt);
            }
        });

        btnPeca19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca19ActionPerformed(evt);
            }
        });

        btnPeca20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca20ActionPerformed(evt);
            }
        });

        btnPeca26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca26ActionPerformed(evt);
            }
        });

        btnPeca27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca27ActionPerformed(evt);
            }
        });

        btnPeca28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca28ActionPerformed(evt);
            }
        });

        btnPeca29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca29ActionPerformed(evt);
            }
        });

        btnPeca30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca30ActionPerformed(evt);
            }
        });

        btnPeca31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca31ActionPerformed(evt);
            }
        });

        btnPeca32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca32ActionPerformed(evt);
            }
        });

        btnPeca33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bolsa.PNG"))); // NOI18N
        btnPeca33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca33ActionPerformed(evt);
            }
        });

        btnPeca34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca34ActionPerformed(evt);
            }
        });

        btnPeca35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca35ActionPerformed(evt);
            }
        });

        btnPeca36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca36ActionPerformed(evt);
            }
        });

        btnPeca37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca37ActionPerformed(evt);
            }
        });

        btnPeca38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeca38ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTabuleiroLayout = new javax.swing.GroupLayout(panelTabuleiro);
        panelTabuleiro.setLayout(panelTabuleiroLayout);
        panelTabuleiroLayout.setHorizontalGroup(
            panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                        .addComponent(btnPeca17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(lblCube2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(276, 276, 276)
                                        .addComponent(lblCube4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTabuleiroLayout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(lblCube1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24))
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addGap(89, 89, 89)
                                                        .addComponent(btnPeca3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addComponent(btnPeca18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnPeca19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(btnPeca2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10)
                                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnPeca4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPeca20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addComponent(btnPeca5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnPeca27, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addComponent(btnPeca26, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnPeca6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCube5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)))))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                .addComponent(btnContract2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)))
                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addComponent(btnPeca28, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(btnPeca29, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnPeca10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addGap(144, 144, 144)
                                                .addComponent(lblCube6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnContract3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPeca9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPeca11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPeca31, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                        .addComponent(lblCube8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)))
                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPeca12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPeca32, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addComponent(btnPeca34, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnPeca35, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addComponent(btnPeca13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(34, 34, 34)
                                                        .addComponent(btnPeca14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(lblCube11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPeca15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPeca36, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                        .addGap(171, 171, 171)
                                        .addComponent(lblCube12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnContract5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13))))
                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                .addComponent(btnPeca7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(btnPeca8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPeca30, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCube7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addComponent(blnBolsaCube, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnPeca33, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                        .addGap(23, 23, 23)
                                                        .addComponent(blnBolsaContract, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addComponent(btnContract4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnContract6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11))
                                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(blnBolsaMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPeca16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPeca37, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                .addComponent(lblCube13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                .addComponent(lblCube14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))))))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                    .addGap(248, 248, 248)
                    .addComponent(lblCube3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1321, Short.MAX_VALUE)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                    .addContainerGap(1185, Short.MAX_VALUE)
                    .addComponent(lblCube10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(384, 384, 384)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                    .addGap(221, 221, 221)
                    .addComponent(btnContract1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1316, Short.MAX_VALUE)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                    .addContainerGap(1072, Short.MAX_VALUE)
                    .addComponent(lblCube9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(497, 497, 497)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                    .addContainerGap(1044, Short.MAX_VALUE)
                    .addComponent(btnPeca38, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(465, 465, 465)))
        );
        panelTabuleiroLayout.setVerticalGroup(
            panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnContract5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btnPeca15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPeca36, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnPeca12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnPeca32, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addComponent(lblCube14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPeca17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                        .addComponent(btnContract4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addComponent(btnContract6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCube2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCube4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCube8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                    .addComponent(btnPeca4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(btnPeca20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(btnPeca28, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPeca7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                    .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnPeca11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnPeca26, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPeca6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPeca29, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPeca10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnPeca8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnPeca5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPeca27, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btnPeca30, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(btnPeca31, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(26, 26, 26)
                                    .addComponent(lblCube5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(109, 109, 109))
                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                    .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(btnContract3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                            .addGap(55, 55, 55)
                                            .addComponent(lblCube6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(80, 80, 80)
                                    .addComponent(btnPeca9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(btnContract2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(btnPeca2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(btnPeca3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnPeca18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(btnPeca19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCube12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCube13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                            .addComponent(btnPeca16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(49, 49, 49)
                                            .addComponent(btnPeca37, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelTabuleiroLayout.createSequentialGroup()
                                            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnPeca13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnPeca14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(37, 37, 37)
                                            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnPeca35, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnPeca34, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(lblCube11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(9, 9, 9)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCube7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69))))
                .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabuleiroLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blnBolsaCube, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCube1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                .addComponent(blnBolsaContract, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPeca33, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                                .addComponent(blnBolsaMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                    .addContainerGap(387, Short.MAX_VALUE)
                    .addComponent(lblCube3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(184, 184, 184)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabuleiroLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(lblCube10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(488, Short.MAX_VALUE)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                    .addContainerGap(468, Short.MAX_VALUE)
                    .addComponent(btnContract1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                    .addContainerGap(399, Short.MAX_VALUE)
                    .addComponent(lblCube9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(170, 170, 170)))
            .addGroup(panelTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabuleiroLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(btnPeca38, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(234, 234, 234)))
        );

        jSeparator1.setForeground(new java.awt.Color(255, 0, 51));

        jSeparator2.setForeground(new java.awt.Color(255, 0, 51));

        btnPlaye1One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye1OneActionPerformed(evt);
            }
        });

        btnPlaye1Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye1TwoActionPerformed(evt);
            }
        });

        btnPlaye1Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye1ThreeActionPerformed(evt);
            }
        });

        btnPlaye1Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye1FourActionPerformed(evt);
            }
        });

        btnPlaye1Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaye1FiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(lblUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPontuacaoUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jSeparator1)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addComponent(lblPontuacaoUser2)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(688, 688, 688)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blnEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPlaye1One, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlaye1Two, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlaye1Five, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlaye1Four, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlaye1Three, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(panelTabuleiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlaye2One, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaye2Two, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaye2Five, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaye2Four, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaye2Three, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblPontuacaoUser2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPontuacaoUser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnPlaye2One, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnPlaye2Two, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnPlaye2Three, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnPlaye2Four, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnPlaye2Five, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTabuleiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaye1One, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnPlaye1Two, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnPlaye1Three, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnPlaye1Four, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnPlaye1Five, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blnEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        String jogador1 = JOptionPane.showInputDialog("Informe o nome do primeiro jogador: ");
        String jogador2 = JOptionPane.showInputDialog("Informe o nome do segundo jogador: ");
        //setando o nome dos jagadores nas label
        lblUser1.setText(jogador1);
        lblUser2.setText(jogador2);
        
        btnIniciar.setVisible(false);
        
        lblPontuacaoUser1.setText("0");
        lblPontuacaoUser2.setText("0");
        
        
       //teste imagens jogador 1
       btnPlaye1One.setIcon(new ImageIcon("\\imagem\\ballio.PNG"));
       btnPlaye1Two.setIcon(new ImageIcon("\\imagem\\canopites.PNG"));
       btnPlaye1Three.setIcon(new ImageIcon("\\imagem\\curculio.PNG"));
       btnPlaye1Four.setIcon(new ImageIcon("\\imagem\\hamilcar.PNG"));
       btnPlaye1Five.setIcon(new ImageIcon("\\imagem\\persa.PNG"));
       
       
       //teste imagens jogador 2
       btnPlaye2One.setIcon(new ImageIcon("\\imagem\\plotus.PNG"));
       btnPlaye2Two.setIcon(new ImageIcon("\\imagem\\pseudolus.PNG"));
       btnPlaye2Three.setIcon(new ImageIcon("\\imagem\\marccus.PNG"));
       btnPlaye2Four.setIcon(new ImageIcon("\\imagem\\herennius.PNG"));
       btnPlaye2Five.setIcon(new ImageIcon("\\imagem\\demetrius.PNG"));
       
       
       //teste de cubes
       lblCube1.setIcon(new ImageIcon("\\imagem\\writeCube.PNG"));
       lblCube2.setIcon(new ImageIcon("\\imagem\\yellowCube.PNG"));
       lblCube3.setIcon(new ImageIcon("\\imagem\\blueCube.PNG"));
       lblCube4.setIcon(new ImageIcon("\\imagem\\redCube.PNG"));
       lblCube5.setIcon(new ImageIcon("\\imagem\\greenCube.PNG"));
       lblCube6.setIcon(new ImageIcon("\\imagem\\writeCube.PNG"));
       lblCube7.setIcon(new ImageIcon("\\imagem\\brownCube.PNG"));
       lblCube8.setIcon(new ImageIcon("\\imagem\\blueCube.PNG"));
       lblCube9.setIcon(new ImageIcon("\\imagem\\writeCube.PNG"));
       lblCube10.setIcon(new ImageIcon("\\imagem\\greenCube.PNG"));
       lblCube11.setIcon(new ImageIcon("\\imagem\\redCube.PNG"));
       lblCube12.setIcon(new ImageIcon("\\imagem\\yellowCube.PNG"));
       lblCube13.setIcon(new ImageIcon("\\imagem\\brownCube.PNG"));
       lblCube14.setIcon(new ImageIcon("\\imagem\\redCube.PNG"));
       
       
       //teste de contract
       btnContract1.setIcon(new ImageIcon("\\imagem\\yellowContract.PNG"));
       btnContract2.setIcon(new ImageIcon("\\imagem\\greenContract.PNG"));
       btnContract3.setIcon(new ImageIcon("\\imagem\\redContract.PNG"));
       btnContract4.setIcon(new ImageIcon("\\imagem\\blueContract.PNG"));
       btnContract5.setIcon(new ImageIcon("\\imagem\\writeContract.PNG"));
       btnContract6.setIcon(new ImageIcon("\\imagem\\brownContract.PNG"));
       
       //teste da bolsa
       blnBolsaCube.setIcon(new ImageIcon("\\imagem\\redCube.PNG"));
       blnBolsaContract.setIcon(new ImageIcon("\\imagem\\greenContract.PNG"));
       blnBolsaMoeda.setIcon(new ImageIcon("\\imagem\\moeda.PNG"));
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void blnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blnEncerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_blnEncerrarActionPerformed

    private void btnPlaye2OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye2OneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye2OneActionPerformed

    private void btnPlaye2TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye2TwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye2TwoActionPerformed

    private void btnPlaye2ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye2ThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye2ThreeActionPerformed

    private void btnPlaye2FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye2FourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye2FourActionPerformed

    private void btnPlaye2FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye2FiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye2FiveActionPerformed

    private void btnPeca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca2ActionPerformed

    private void btnPeca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca3ActionPerformed

    private void btnPeca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca4ActionPerformed

    private void btnPeca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca5ActionPerformed

    private void btnPeca6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca6ActionPerformed

    private void btnPeca7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca7ActionPerformed

    private void btnPeca8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca8ActionPerformed

    private void btnPeca9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca9ActionPerformed

    private void btnPeca10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca10ActionPerformed

    private void btnPeca11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca11ActionPerformed

    private void btnPeca12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca12ActionPerformed

    private void btnPeca13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca13ActionPerformed

    private void btnPeca14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca14ActionPerformed

    private void btnPeca15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca15ActionPerformed

    private void btnPeca16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca16ActionPerformed

    private void btnPeca17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca17ActionPerformed

    private void btnPeca18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca18ActionPerformed

    private void btnPeca19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca19ActionPerformed

    private void btnPeca20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca20ActionPerformed

    private void btnPeca26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca26ActionPerformed

    private void btnPeca27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca27ActionPerformed

    private void btnPeca28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca28ActionPerformed

    private void btnPeca29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca29ActionPerformed

    private void btnPeca30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca30ActionPerformed

    private void btnPeca31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca31ActionPerformed

    private void btnPeca32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca32ActionPerformed

    private void btnPeca33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca33ActionPerformed

    private void btnPeca34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca34ActionPerformed

    private void btnPeca35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca35ActionPerformed

    private void btnPeca36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca36ActionPerformed

    private void btnPeca37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca37ActionPerformed

    private void btnPlaye1OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye1OneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye1OneActionPerformed

    private void btnPlaye1TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye1TwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye1TwoActionPerformed

    private void btnPlaye1ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye1ThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye1ThreeActionPerformed

    private void btnPlaye1FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye1FourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye1FourActionPerformed

    private void btnPlaye1FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaye1FiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaye1FiveActionPerformed

    private void btnPeca38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeca38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeca38ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabuleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blnBolsaContract;
    private javax.swing.JButton blnBolsaCube;
    private javax.swing.JButton blnBolsaMoeda;
    private javax.swing.JButton blnEncerrar;
    private javax.swing.JButton btnContract1;
    private javax.swing.JButton btnContract2;
    private javax.swing.JButton btnContract3;
    private javax.swing.JButton btnContract4;
    private javax.swing.JButton btnContract5;
    private javax.swing.JButton btnContract6;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPeca10;
    private javax.swing.JButton btnPeca11;
    private javax.swing.JButton btnPeca12;
    private javax.swing.JButton btnPeca13;
    private javax.swing.JButton btnPeca14;
    private javax.swing.JButton btnPeca15;
    private javax.swing.JButton btnPeca16;
    private javax.swing.JButton btnPeca17;
    private javax.swing.JButton btnPeca18;
    private javax.swing.JButton btnPeca19;
    private javax.swing.JButton btnPeca2;
    private javax.swing.JButton btnPeca20;
    private javax.swing.JButton btnPeca26;
    private javax.swing.JButton btnPeca27;
    private javax.swing.JButton btnPeca28;
    private javax.swing.JButton btnPeca29;
    private javax.swing.JButton btnPeca3;
    private javax.swing.JButton btnPeca30;
    private javax.swing.JButton btnPeca31;
    private javax.swing.JButton btnPeca32;
    private javax.swing.JButton btnPeca33;
    private javax.swing.JButton btnPeca34;
    private javax.swing.JButton btnPeca35;
    private javax.swing.JButton btnPeca36;
    private javax.swing.JButton btnPeca37;
    private javax.swing.JButton btnPeca38;
    private javax.swing.JButton btnPeca4;
    private javax.swing.JButton btnPeca5;
    private javax.swing.JButton btnPeca6;
    private javax.swing.JButton btnPeca7;
    private javax.swing.JButton btnPeca8;
    private javax.swing.JButton btnPeca9;
    private javax.swing.JButton btnPlaye1Five;
    private javax.swing.JButton btnPlaye1Four;
    private javax.swing.JButton btnPlaye1One;
    private javax.swing.JButton btnPlaye1Three;
    private javax.swing.JButton btnPlaye1Two;
    private javax.swing.JButton btnPlaye2Five;
    private javax.swing.JButton btnPlaye2Four;
    private javax.swing.JButton btnPlaye2One;
    private javax.swing.JButton btnPlaye2Three;
    private javax.swing.JButton btnPlaye2Two;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lblCube1;
    private javax.swing.JButton lblCube10;
    private javax.swing.JButton lblCube11;
    private javax.swing.JButton lblCube12;
    private javax.swing.JButton lblCube13;
    private javax.swing.JButton lblCube14;
    private javax.swing.JButton lblCube2;
    private javax.swing.JButton lblCube3;
    private javax.swing.JButton lblCube4;
    private javax.swing.JButton lblCube5;
    private javax.swing.JButton lblCube6;
    private javax.swing.JButton lblCube7;
    private javax.swing.JButton lblCube8;
    private javax.swing.JButton lblCube9;
    private javax.swing.JLabel lblPontuacaoUser1;
    private javax.swing.JLabel lblPontuacaoUser2;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JLabel lblUser2;
    private javax.swing.JPanel panelTabuleiro;
    // End of variables declaration//GEN-END:variables
}
